name: Continuous Deployment
run-name: ${{ github.actor }} is running continuous deployment

on:
  workflow_dispatch:
  push:
    branches:
       - main

env:
  DESIGN_BRANCH: design-token-updates


jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Print Details
        run: echo "Details -> event - (${{ github.event_name }}) os - (${{ runner.os }}) branch - (${{ github.ref }})"
      - name: Run Pipeline CD script
        run:  echo "Not Complete"
      - uses: actions/checkout@v3
      - name: Set Git config to github actions user
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge default branch into design branch
        run: |
          git fetch --unshallow
          git checkout $DESIGN_BRANCH
          git pull
          git merge --no-ff ${{ github.event.repository.default_branch }}
          git push




