name: Continuous Integration
run-name: ${{ github.actor }} is running continuous integration

on:
  # right now, publishing is only run manually from github actions
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    # required that main has all the correct package versions for every package that is being published
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Deploy Packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish:all